global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: "ingestion-service"
    static_configs:
      - targets: ["ingestion-service:9090"]
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: "redis"
    static_configs:
      - targets: ["redis:6379"]
    metrics_path: /metrics

  - job_name: "neo4j"
    static_configs:
      - targets: ["neo4j:2004"]
    metrics_path: /metrics

  - job_name: "qdrant"
    static_configs:
      - targets: ["qdrant:6333"]
    metrics_path: /metrics